repos:

-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.10.0
    hooks:
      - id: isort
        name: isort

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: requirements
        name: requirements.txt is current
        entry: poetry export -o requirements.txt
        pass_filenames: false
        language: system
